export const SET_ACTION = 'SET_ACTION';
export const SET_SYMBOL = 'SET_SYMBOL';
export const SET_LIST = 'SET_LIST';
export const SET_QUANTITY = 'SET_QUANTITY';
export const SET_TYPE = 'SET_TYPE';
export const SET_LIMIT = 'SET_LIMIT';
export const SET_TERM = 'SET_TERM';
export const SET_SYMBOL_INFO = 'SET_SYMBOL_INFO';

export const SET_OPEN_BUY_ORDER_CONFIRMATION = 'SET_OPEN_BUY_ORDER_CONFIRMATION';
export const SET_OPEN_SELL_ORDER_CONFIRMATION = 'SET_OPEN_SELL_ORDER_CONFIRMATION';
export const SET_OPEN_ORDER_FULFILL = 'SET_OPEN_ORDER_FULFILLED';
export const SET_BALANCE = 'SET_BALANCE';
export const SET_ORDER_HISTORY = 'SET_ORDER_HISTORY';
export const SET_MARKET_VALUE_OF_LONG_POSITIONS = 'SET_MARKET_VALUE_OF_LONG_POSITIONS';
export const SET_TRADES_MADE = 'SET_TRADES_MADE';
export const SET_CURRENT_VALUES = 'SET_CURRENT_VALUES';